# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Z.W. Miller
tagline:          ''
description:      'A moderately okay data science blog'
url:              http://zachmetis.github.io
baseurl:          /

author:
  name:           'Zach Miller'
  url:            https://zwmiller.com


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zachMetis/zachmetis.github.io

gems:           [jekyll-paginate, jekyll-gist]
paginate:         5
